### ISSUE TITLE
in the boltzmann_wealth_distribution.jl，my julia version is 1.1，found the issue as below，please have a look：）

### ISSUE THREAD

**Issue by LengyanReader** [kavir1698/Agents.jl#1]
![image](https://user-images.githubusercontent.com/10557968/53540753-bfeed180-3b51-11e9-9446-37b4319e13a3.png)

**Comment by kavir1698** [comment]
Thanks for mentioning this issue.
You get this error because `MyGrid` and `MyAgent` types accept two dimensional position coordinates, but your `griddims` is three-dimensional. It words if you use `griddims=(5,5)`.

**Comment by kavir1698** [comment]
Nevertheless, there was a typo in the `instantiate_model` function that is fixed now. Try the latest commit.

**Comment by LengyanReader** [comment]
> 
> 
> Nevertheless, there was a typo in the `instantiate_model` function that is fixed now. Try the latest commit.

Thank you so much for your contribution
