### ISSUE TITLE
[Doc] Possible improvements of the documentation homepage

### ISSUE THREAD

**Issue by Datseris** [kavir1698/Agents.jl#16]
Hi there,

As part of the JOSS review, I'd like to suggest the following improvements of the documentation, that you could implement optionally if you want to:

- [x] Itemize the components of the paragraph starting with `Agents.jl provides users with core components that make it easy to build ABMS, run them in batch, collect model outputs, and visualize the results...`. Specifically, the bolder words could be made to start items. This will increase readability and make overviewing easier.
- [x] The documentation starts immediately with the functionality of the package. Although this is fine assuming the newcomer user already knows what ABM is, it may not be optimal for people that check out Agents.jl but are not completely familiar with ABM. I'd suggest to add a small new paragraph in the intro that in a couple of sentences summarizes ABM and provides a physical / social example.
- [x] Although a very detailed exposure of existing _software_ is made in the introduction, there may be a lack of resources from the scientific perspective. In the aforementioned new paragraph I'd suggest to also link some standard textbooks or webpages on the subject.

(will be updating this as I read more of the Docs)

**Comment by kavir1698** [comment]
Hi,
Thank you for your comments. I have included the first three suggestions.

**Comment by Datseris** [comment]
Awesome! There seems to be some typo in the sections though:

![image](https://user-images.githubusercontent.com/19669089/62222405-f7d99980-b3bb-11e9-8308-2da24e5283cc.png)

**Comment by kavir1698** [comment]
Oops. The tag wasn't supposed to be visible. I will have to remove it altogether.
