### ISSUE TITLE
[Doc] Document visualization

### ISSUE THREAD

**Issue by Datseris** [kavir1698/Agents.jl#21]
Hi, I am running the `examples/schelling.jl` file. It runs without a problem, its final output being:
```
0: blue
1: red
0: blue
1: red
```
Isn't the file supposed to plot something? Seems like the name of the function `visualize_2D_agent_distribution` intends to plot. Can someone confirm whether this function does plot for them?

I am running windows 10. Agents master branch. Installation worked fine, but I am getting the problem of #17

**Comment by kavir1698** [comment]
Hi, the plots are saved in PDF files in the same directory that the file is
run.

**Comment by Datseris** [comment]
Alright, this was not stated in the docstring of `visualize_2D_agent_distribution`. Please document in the relevant visualization functions how to visualize, where the visualization is done, whether it is displayed or not, etc.

In addition, I would highly recommend to add an argument to these functions so that the user chooses the save directory as well as the save name of the files.

**Comment by kavir1698** [comment]
The docstrings are updated and an argument `saveloc` added to the functions to choose a save location of the plots (https://github.com/kavir1698/Agents.jl/commit/d39dba818a31e7e0e4c3639bf735b0f6607951f9).
