### ISSUE TITLE
[DOC] Statement of the APIs

### ISSUE THREAD

**Issue by Datseris** [kavir1698/Agents.jl#22]
From my understanding reading the docs, Agents seems to define some APIs that the user-defined types must follow. For example, it seems to me that `Model` and `scheduler` functions have a specific form, or should have a specific form.

is this true?

If yes, I think this has to be stated somewhere explicitly and not only via examples. E.g. the expected fields that subtypes of `AbstractModel` should have.

I am now looking at the Schelling's segregation model doc page. I realize that what I ask here is partly described there. This is (in my personal opinion) not an intuitive mix. API and Package Workflow should have their own dedicated page, and examples should follow after.

My suggestion would be to move the first section of that page to a dedicated page, and enrich it with API instructions for `AbstractModel`, `scheduler`, etc...

**Comment by Datseris** [comment]
Hm, the more I read the Schelling's model tutorial, the more I see that what I ask for is already existing. This could be solved with minimal effort, by making Schelling's tutorial a first-level page by itself (instead of being grouped in the examples) and changing titles and making everything a bit more visible.

Some other title is necessary, so that it is obvious from a glance that this page does serve as an "introduction" to Agents.jl. I suggest to make the First level title `Agent's.jl Architecture` and add a second title later on `Schelling's segregation model Example`.

(what I said above, to state the expected API **independently** of an example, is still very useful)

**Comment by Datseris** [comment]
The [Table of Contents](https://kavir1698.github.io/Agents.jl/dev/#Table-of-contents-1) also starts with the forest fire model. Some re-organization there could help as well, so that it starts with basic API introduction instead.

**Comment by kavir1698** [comment]
Hi,
Thanks for the suggestions. I was on vacation. I will try to address your comments as soon as possible.

**Comment by kavir1698** [comment]
The docs are now refactored as you suggested.

**Comment by Datseris** [comment]
Cool, thanks, I'll have a look soon!

**Comment by Datseris** [comment]
I am reading the new documentation currently. I have some comments that might sound nit-picky but I think can really help improve the docs. Recall that I am in no way a user already familiar with Agents.jl and thus my comments (I believe) do give you the impression of what a newcomer would think.

---

Anyway, here goes: I think the "Defining a space object" from the documentation is unecessary. I think the functionality that a user can define their own grid is cool, but way too advanced for an introductory tutorial. Maybe a different tutorial on "making your own space" is in order, and instead in the introductory tutorial you can use the function `grid`, and reference it using the syntax ``[`grid`](@ref)``. 

I stand that understanding LightGraphs.jl should not be necessary to use the basics of Agents.jl, but in order to create a "Space" by yourself, you really have to know LightGraphs.jl. In fact, I don't at all understand why one has to create a space by themselves.

---

The usage of terms "grid" and "space" is confusing, because they don't really have a proper definition. Do they mean the same thing? (for someone with my background, condensed matter, they could)  What does "grid" mean? The documentation of `grid` states:
```
Return a grid based on its dimensions...
```
but does not state what a grid actually is. By running the function I realize it is a `SimpleGraph`. This should be stated in the documentation string explicitly. Users not already familiar with Agents.jl will have to guess what grid means.

**Comment by kavir1698** [comment]
Thank you.
Indeed, understanding LightGraphs.jl is _not_ necessary for using Agents.jl. For any regular space, the user only needs to provide dimensions of the space. This is what happens in all of the examples. So there is no direct interaction with LightGraphs.jl.

I have mentioned that it is possible for users to create and input a custom irregular space for their simulations. This is a useful option as not all simulations happen in a regular grid.

I can add a description to docstrings defining a grid.

**Comment by Datseris** [comment]
@kavir1698 I'll close this (and thus fullfill the point in the JOSS review) once you simply state in the docstrings of `grid` that they return a `SimpleGraph`. Nothing more is currently necessary and implementing #24 is not necessary for the review.

**Comment by kavir1698** [comment]
Cool, https://github.com/kavir1698/Agents.jl/commit/9b16776ef69dcdb277a0bfed5cc6f03bf82ca0e6 addresses your comment.
