### ISSUE TITLE
Proposal: Scheduler type

### ISSUE THREAD

**Issue by Datseris** [kavir1698/Agents.jl#23]
Hi there,

I think it might be worth it to implement a `Scheduler` type that acts as a functor. The inspiration for this comes from:
```julia
"""
    partial_activation(model::AbstractModel)
At each step, activates only `activation_prob` number of randomly chosen of individuals with a `activation_prob` probability. `activation_prob` should be a field in the model and between 0 and 1.
"""
function partial_activation(model::AbstractModel)
  agentnum = nagents(model)
  return randsubseq(1:agentnum, model.activation_prob)
end
```

This function requires the `model` to have a field `activation_prob`. This is restrictive. In addition, this `activation_prob` is (in my intuition) not a property of the model, but specific for the scheduler.

Wouldn't it be more intuitive to define something like:
```julia
abstract type Scheduler end
struct AsAdded <: Scheduler end
struct RandomScheduler <: Scheduler end
struct PartialScheduler{R<:Real} <: Scheduler
    probability::R
end

function (s::AsAdded)(model::AbstractModel)
    # stuff
end

function (s::PartialScheduler)(model::AbstractModel)
  agentnum = nagents(model)
  return randsubseq(1:agentnum, s.probability)
end
```

? just a suggestion, but this would make it easier to document the API and also leverage multiple dispatch.

---

The documentation would then be straight forward:

1. Define a subtype of `Scheduler`.
2. Define a functor dispatch on `(s::Scheduler)(model::AbstractModel)`
3. Be sure the return type of your scheduler is `TypeUsedByAgents.jl`

**Comment by Datseris** [comment]
But of course, this may all be solved by better documenting the API in general, as suggested by #22 . Still, it is worth considering having a scheduler type, might make the code cleaner through multiple dispatch.

**Comment by kavir1698** [comment]
I think this will make it a bit more difficult for the user. Currently, if they need a different scheduler, they only have to define a function that returns agents' indices in a desired order.

**Comment by Datseris** [comment]
Fair enough, and in addition what I state here is currently possible anyway. E.g. if I were to use Agents.jl for scientific purposes, I would do it like I suggested here and everything would "just work".

Maybe when porting the examples into the Literate.jl format, I will make one example use this, just as a showcase that it is possible.
