### ISSUE TITLE
Use Tagbot to tag releases

### ISSUE THREAD

**Issue by Datseris** [kavir1698/Agents.jl#25]
So that a new version is updated in the Julia package ecosystem.

1. Install JuliaRegistrator: and https://github.com/JuliaRegistries/Registrator.jl/#registrator tagbot : https://github.com/apps/julia-tagbot 
2. Update `Project.toml` to match the version you want to tag
3. Go into the commit and comment "@JuliaRegistrator register()"
4. Win!

**Comment by kavir1698** [comment]
OK, thanks for the tips. I have followed along. The pull request created by JuliaRegistrator does not get merged automatically and I don't see anywhere to confirm it. What am I missing here?
