### ISSUE TITLE
Error when running Schelling.jl (again)

### ISSUE THREAD

**Issue by sbacelar** [kavir1698/Agents.jl#28]
When running `Schelling.jl` using `Juno`(in Julia 1.2) when:
```
# Instantiate the model with 370 agents on a 20 by 20 grid. 
model = instantiate_model(numagents=370, griddims=(20,20), min_to_be_happy=3)
```
I receive the following error:
`function Grid does not accept keyword arguments`
I don't know if this is related with ([#10](https://github.com/kavir1698/Agents.jl/issues/10))

**Comment by kavir1698** [comment]
It's not because of #10. I noticed `LightGraphs` has made some syntax change. https://github.com/kavir1698/Agents.jl/commit/5580f03d8f749102429076a2903166aad85fd31b should fix the error. Update to the latest changes from the master branch and it should work.

**Comment by sbacelar** [comment]
I'm using now `Agents#master`. Now it works, thanks.
