### ISSUE TITLE
Error with Cairo when using Agents

### ISSUE THREAD

**Issue by sbacelar** [kavir1698/Agents.jl#4]
When I try `using Agents` I get the following error:
```
┌ Info: Precompiling Agents [46ada45e-f475-11e8-01d0-f70cc89e6671]
└ @ Base loading.jl:1186
ERROR: LoadError: Cairo not properly installed. Please run
Pkg.build("Cairo")
```
After trying to Pkg.build("Cairo") I get:
```
┌ Error: Error building `Cairo`: 
│ 
│ signal (11): Segmentation fault: 11
│ in expression starting at /Users/sergiobacelar/.julia/packages/Cairo/CXPG1/deps/build.jl:165
│ _platform_strcmp at /usr/lib/system/libsystem_platform.dylib (unknown line)
│ Allocations: 19789750 (Pool: 19786916; Big: 2834); GC: 44
└ @ Pkg.Operations /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.1/Pkg/src/Operations.jl:1075
```

**Comment by kavir1698** [comment]
Your problem seems to be with the Cairo installation. Better check it with
them.

**Comment by sbacelar** [comment]
I did it now. I think it is a known issue.

**Comment by sbacelar** [comment]
I removed `Agents` and finally, I could update `Cairo` version to 0.6.0. Now when I try to add `Agents` I get (in macOS and Linux):
```
(v1.1) pkg> add Agents
 Resolving package versions...
ERROR: Unsatisfiable requirements detected for package VegaLite [112f6efa]:
 VegaLite [112f6efa] log:
 ├─possible versions are: [0.0.1-0.0.3, 0.1.0, 0.2.0, 0.3.0-0.3.4, 0.4.0, 0.5.0-0.5.3, 0.6.0] or uninstalled
 ├─restricted by compatibility requirements with Agents [46ada45e] to versions: [0.0.1-0.0.3, 0.1.0, 0.2.0, 0.3.0-0.3.4, 0.4.0, 0.5.0-0.5.3, 0.6.0]
 │ └─Agents [46ada45e] log:
 │   ├─possible versions are: 1.1.0 or uninstalled
 │   └─restricted to versions * by an explicit requirement, leaving only versions 1.1.0
 ├─restricted by julia compatibility requirements to versions: [0.3.4, 0.4.0, 0.5.0-0.5.3, 0.6.0] or uninstalled, leaving only versions: [0.3.4, 0.4.0, 0.5.0-0.5.3, 0.6.0]
 └─restricted by compatibility requirements with Cairo [159f3aea] to versions: 0.0.1-0.0.3 or uninstalled — no versions left
   └─Cairo [159f3aea] log:
     ├─possible versions are: [0.0.1, 0.2.0-0.2.35, 0.3.0-0.3.1, 0.4.0, 0.5.0-0.5.6, 0.6.0] or uninstalled
     └─restricted to versions 0.6.0 by an explicit requirement, leaving only versions 0.6.0
```

**Comment by kavir1698** [comment]
I have updated the package requirements of `Agents`. Could you try to install from master?
`]add Agents#master`

**Comment by sbacelar** [comment]
I have got an error when trying to install from master:
```
(v1.1) pkg> add Agents#master
  Updating git-repo `https://github.com/kavir1698/Agents.jl.git`
 Resolving package versions...
ERROR: Unsatisfiable requirements detected for package VegaLite [112f6efa]:
 VegaLite [112f6efa] log:
 ├─possible versions are: [0.0.1-0.0.3, 0.1.0, 0.2.0, 0.3.0-0.3.4, 0.4.0, 0.5.0-0.5.3, 0.6.0] or uninstalled
 ├─restricted to versions * by Agents [46ada45e], leaving only versions [0.0.1-0.0.3, 0.1.0, 0.2.0, 0.3.0-0.3.4, 0.4.0, 0.5.0-0.5.3, 0.6.0]
 │ └─Agents [46ada45e] log:
 │   ├─possible versions are: 1.1.0 or uninstalled
 │   └─Agents [46ada45e] is fixed to version 1.1.0
 ├─restricted by julia compatibility requirements to versions: [0.3.4, 0.4.0, 0.5.0-0.5.3, 0.6.0] or uninstalled, leaving only versions: [0.3.4, 0.4.0, 0.5.0-0.5.3, 0.6.0]
 └─restricted by compatibility requirements with Cairo [159f3aea] to versions: 0.0.1-0.0.3 or uninstalled — no versions left
   └─Cairo [159f3aea] log:
     ├─possible versions are: [0.0.1, 0.2.0-0.2.35, 0.3.0-0.3.1, 0.4.0, 0.5.0-0.5.6, 0.6.0] or uninstalled
     └─restricted to versions 0.6.0 by an explicit requirement, leaving only versions 0.6.0
```

**Comment by kavir1698** [comment]
It is an incompatibility between Julia 1.x requirements for VegaLite (0.3.4, 0.4.0, 0.5.0-0.5.3, 0.6.0) and Cairo's requirement  (strangely only 0.0.1-0.0.3). Are you sure you have installed the latest Cairo? Could you try to install VegaLite separately?

**Comment by sbacelar** [comment]
The Cairo version is 0.6.0 which I think is the last one. I did ]up. When I try to add VegaLite I get:
```
(v1.1) pkg> add VegaLite
 Resolving package versions...
ERROR: Unsatisfiable requirements detected for package VegaLite [112f6efa]:
 VegaLite [112f6efa] log:
 ├─possible versions are: [0.0.1-0.0.3, 0.1.0, 0.2.0, 0.3.0-0.3.4, 0.4.0, 0.5.0-0.5.3, 0.6.0] or uninstalled
 ├─restricted to versions * by an explicit requirement, leaving only versions [0.0.1-0.0.3, 0.1.0, 0.2.0, 0.3.0-0.3.4, 0.4.0, 0.5.0-0.5.3, 0.6.0]
 ├─restricted by julia compatibility requirements to versions: [0.3.4, 0.4.0, 0.5.0-0.5.3, 0.6.0] or uninstalled, leaving only versions: [0.3.4, 0.4.0, 0.5.0-0.5.3, 0.6.0]
 └─restricted by compatibility requirements with Cairo [159f3aea] to versions: 0.0.1-0.0.3 or uninstalled — no versions left
   └─Cairo [159f3aea] log:
     ├─possible versions are: [0.0.1, 0.2.0-0.2.35, 0.3.0-0.3.1, 0.4.0, 0.5.0-0.5.6, 0.6.0] or uninstalled
     └─restricted to versions 0.6.0 by an explicit requirement, leaving only versions 0.6.0
```

**Comment by kavir1698** [comment]
Yeah, same as before, Cairo is requiring only an old version of VegaLite.
This is weird. If it was me, I would either test it with a fresh
installation of Julia or follow it up with Cairo. Sorry I cannot be of
better help.

**Comment by sbacelar** [comment]
I think using a fresh installation of Julia is not an option because the same happened also in my Linux computer, but I opened an issue in `VegaLite` and in `Cairo`.

**Comment by kavir1698** [comment]
Unfortunately, I cannot replicate your errors. I have installed it on three different machines without a problem.

**Comment by sbacelar** [comment]
After a **fresh** Julia installation on macOS Mojave I added only one package `Agents` and then I got the same problem with Cairo:
 ```
Building Cairo ───────────→ `~/.julia/packages/Cairo/CXPG1/deps/build.log`
┌ Error: Error building `Cairo`:
│ ==> Installing graphite2 from staticfloat/juliatranslated
│ ==> Downloading https://homebrew.bintray.com/bottles/graphite2-1.3.13.mojave.bottle.tar.gz
│ Already downloaded: /Users/sergiobacelar/Library/Caches/Homebrew.jl/downloads/36f9054572b26853c4726b48a48041476190c6e2069d088be488bd9489445ade--graphite2-1.3.13.mojave.bottle.tar.gz
│ ==> Pouring graphite2-1.3.13.mojave.bottle.tar.gz
│ 🍺  /Users/sergiobacelar/.julia/packages/Homebrew/s09IX/deps/usr/Cellar/graphite2/1.3.13: 18 files, 232.2KB
│ Warning: Already linked: /Users/sergiobacelar/.julia/packages/Homebrew/s09IX/deps/usr/Cellar/graphite2/1.3.13
│
│ signal (11): Segmentation fault: 11
│ in expression starting at /Users/sergiobacelar/.julia/packages/Cairo/CXPG1/deps/build.jl:165
│ _platform_strcmp at /usr/lib/system/libsystem_platform.dylib (unknown line)
│ Allocations: 20694732 (Pool: 20691713; Big: 3019); GC: 46
└ @ Pkg.Operations /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.1/Pkg/src/Operations.jl:1075
```

**Comment by sbacelar** [comment]
I received this from Cairo.jl:

> @sbacelar yes, the reason is Agents uses an older version of Cairo. You may now edit the build.jl file according to #279 (comment) but then use ] build Cairo and not ]up; alternatively, you may ask Agents to use the current version of Cairo?

**Comment by kavir1698** [comment]
> After a **fresh** Julia installation on macOS Mojave I added only one package `Agents` and then I got the same problem with Cairo:
> 
> ```
> Building Cairo ───────────→ `~/.julia/packages/Cairo/CXPG1/deps/build.log`
> ┌ Error: Error building `Cairo`:
> │ ==> Installing graphite2 from staticfloat/juliatranslated
> │ ==> Downloading https://homebrew.bintray.com/bottles/graphite2-1.3.13.mojave.bottle.tar.gz
> │ Already downloaded: /Users/sergiobacelar/Library/Caches/Homebrew.jl/downloads/36f9054572b26853c4726b48a48041476190c6e2069d088be488bd9489445ade--graphite2-1.3.13.mojave.bottle.tar.gz
> │ ==> Pouring graphite2-1.3.13.mojave.bottle.tar.gz
> │ 🍺  /Users/sergiobacelar/.julia/packages/Homebrew/s09IX/deps/usr/Cellar/graphite2/1.3.13: 18 files, 232.2KB
> │ Warning: Already linked: /Users/sergiobacelar/.julia/packages/Homebrew/s09IX/deps/usr/Cellar/graphite2/1.3.13
> │
> │ signal (11): Segmentation fault: 11
> │ in expression starting at /Users/sergiobacelar/.julia/packages/Cairo/CXPG1/deps/build.jl:165
> │ _platform_strcmp at /usr/lib/system/libsystem_platform.dylib (unknown line)
> │ Allocations: 20694732 (Pool: 20691713; Big: 3019); GC: 46
> └ @ Pkg.Operations /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.1/Pkg/src/Operations.jl:1075
> ```

Isn't this a problem with Cairo on macOS? I see on their issue list that installing from `master` is helpful:

https://github.com/JuliaGraphics/Cairo.jl/issues/271#issuecomment-485285220

**Comment by kavir1698** [comment]
> I received this from Cairo.jl:
> 
> > @sbacelar yes, the reason is Agents uses an older version of Cairo. You may now edit the build.jl file according to #279 (comment) but then use ] build Cairo and not ]up; alternatively, you may ask Agents to use the current version of Cairo?
> 
> The current version of `Cairo` is 0.6.0.

`Agents` is using Cairo 5.6. I will follow it on the issue you opened there.

**Comment by kavir1698** [comment]
I now see that Agents has to use Cairo v0.5.6 because that is a bound by VegaLite. So I cannot make `Agents` to use v0.6.0. Nevertheless, Cairo v0.5.6 does not seem to be a problem, according to your error messages.

**Comment by sbacelar** [comment]
It is now [solved](https://github.com/JuliaGraphics/Cairo.jl/issues/279) with `Cairo`. Sorry for bothering you.

**Comment by kavir1698** [comment]
Glad to hear that.
