### ISSUE TITLE
Error: SimpleGraph not defined in Forest fire model

### ISSUE THREAD

**Issue by sbacelar** [kavir1698/Agents.jl#8]
When running `Forest fire model` on Jupyter Lab I get:
```
mutable struct MyGrid{T<:Integer, Y<:AbstractVector} <: AbstractSpace
  dimensions::Tuple{T, T}
  space::SimpleGraph
  agent_positions::Y  # an array of arrays for each grid node
end
```

```
UndefVarError: SimpleGraph not defined

Stacktrace:
 [1] top-level scope at none:0 
```

**Comment by kavir1698** [comment]
I cannot replicate the error under Windows. But I get the error under Ubuntu. `using LightGraphs` should solve it. Can you confirm?

**Comment by sbacelar** [comment]
Yes, `using LightGraphs` solved this problem in macOS.

**Comment by kavir1698** [comment]
Ok, the error is because you were not on the latest version of Agents. Updating should solve it. You won't need to import `LightGraphs`.

**Comment by sbacelar** [comment]
I have the version 1.1.0 after updating.
